---
development:
  dialect: postgres
  database: subscription_service_development
  user: postgres
  password: postgres
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/subscription_service_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/subscription_service_production?sslmode=disable"}}
